[build]
  base = "/"
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/data/*.json"]  # For any local data files

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_BASE = "https://api.trs-alliance.com"  # Example env var

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Optional performance monitoring
[[plugins]]
  package = "@netlify/plugin-lighthouse"
