# netlify.toml (Managed by DeepSeek)
[build]
  command = "npm run export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    debug = true

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "@netlify/plugin-inline-critical-css"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

