[build]
  base = "/"                      # Adjust only if your project isn't at repo root
  publish = "dist"               # Folder to publish (from `npm run build`)
  command = "npm run build"      # Build command
  functions = "netlify/functions" # Path to Netlify Functions

[functions]
  node_bundler = "esbuild"       # Optional: Faster bundling, modern syntax

[build.environment]
  NODE_VERSION = "20"            # Match your local/dev Node version
  NPM_FLAGS = "--legacy-peer-deps" # Optional: if you hit dependency issues

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
