name: 📊 TRS SEO Audit

on:
  push:
    branches:
      - main

jobs:
  seo-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run SEO Validation
        run: node cli/index.js seo --agent=deepseek --target=meta